<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
	<TargetFramework>net8.0</TargetFramework>
	<IsPackable>false</IsPackable>
	<RootNamespace>SmartArchive.Tests</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
	<PackageReference Include="xunit" Version="2.4.2" />
	<PackageReference Include="xunit.runner.visualstudio" Version="2.4.5" />
	<PackageReference Include="Moq" Version="4.20.0" />
	<PackageReference Include="Microsoft.AspNetCore.Mvc.Testing" Version="8.0.0" />
  </ItemGroup>
  <ItemGroup>
	<ProjectReference Include="$(SolutionDir)src\SmartArchive.Api\SmartArchive.Api.csproj" />
	<ProjectReference Include="$(SolutionDir)src\SmartArchive.Infrastructure\SmartArchive.Infrastructure.csproj" />
  </ItemGroup>
</Project>